name: forward-push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: dev
    paths-ignore:
      - '.github/workflows/publish.yml'
      - 'tools/ci/make-pkg.ps1'

jobs:
  forward-push:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'axmolengine/axmol' }}
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.AX_TRIGGER_SITE_TOKEN }}
        repository: axmolengine/axmolengine.github.io
        event-type: forward-push
